import { GoogleGenAI } from '@google/genai';

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

if (!GEMINI_API_KEY) {
    console.warn('Missing VITE_GEMINI_API_KEY environment variable');
}

const ai = new GoogleGenAI({
    apiKey: GEMINI_API_KEY,
});

export interface GeminiImageResult {
    imageData: string; // base64 encoded image data
    mimeType: string;
    text?: string;
}

// Helper function to extract base64 data and mime type from a data URL
function parseDataUrl(dataUrl: string): { base64: string; mimeType: string } {
    const matches = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
    if (!matches) {
        throw new Error('Invalid data URL format');
    }
    return {
        mimeType: matches[1],
        base64: matches[2],
    };
}

export async function generateImageWithGemini(
    prompt: string,
    imageDataUrl?: string
): Promise<GeminiImageResult> {
    const config = {
        responseModalities: ['IMAGE', 'TEXT'] as string[],
        imageConfig: {
            aspectRatio: '1:1' as const,
        },
    };

    const model = 'gemini-2.5-flash-image';

    // Build the parts array - include image if provided
    const parts: Array<{ text: string } | { inlineData: { mimeType: string; data: string } }> = [];

    // Add image first if provided (for image editing/transformation)
    if (imageDataUrl) {
        const { base64, mimeType } = parseDataUrl(imageDataUrl);
        parts.push({
            inlineData: {
                mimeType: mimeType,
                data: base64,
            },
        });
    }

    // Add text prompt
    parts.push({
        text: prompt,
    });

    const contents = [
        {
            role: 'user' as const,
            parts: parts,
        },
    ];

    const response = await ai.models.generateContentStream({
        model,
        config,
        contents,
    });

    let resultImage: GeminiImageResult | null = null;
    let resultText = '';

    for await (const chunk of response) {
        if (!chunk.candidates || !chunk.candidates[0].content || !chunk.candidates[0].content.parts) {
            continue;
        }

        const parts = chunk.candidates[0].content.parts;

        for (const part of parts) {
            if ('inlineData' in part && part.inlineData) {
                const inlineData = part.inlineData;
                resultImage = {
                    imageData: inlineData.data || '',
                    mimeType: inlineData.mimeType || 'image/png',
                };
            } else if ('text' in part && part.text) {
                resultText += part.text;
            }
        }
    }

    if (!resultImage) {
        throw new Error('No image was generated by Gemini');
    }

    return {
        ...resultImage,
        text: resultText || undefined,
    };
}

// Helper function to convert base64 to data URL
export function base64ToDataUrl(base64: string, mimeType: string): string {
    return `data:${mimeType};base64,${base64}`;
}
